[package]
name = "aqa-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline_colorization = "0.1.6"
strsim = "0.11.1"
unicode-width = "0.1.11"
