name: build

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4 
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: build
      run: cargo build --verbose
